name: pdf_summerizer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.14.2
  uuid: ^4.5.3
  file_picker: ^8.0.0
  flutter_dotenv: ^6.0.1
  http: ^1.2.0
  syncfusion_flutter_pdf: ^27.1.48
  pdfrx_engine: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env